# Generated by Django 3.1.5 on 2021-01-27 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0003_remove_library_user'),
        ('users', '0002_user_library'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='library',
            field=models.OneToOneField(default='나의 서재', on_delete=django.db.models.deletion.CASCADE, related_name='users', to='library.library'),
        ),
    ]
