# Generated by Django 3.1.5 on 2021-01-27 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20210127_1950'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='pub_date_p',
            new_name='pub_date',
        ),
        migrations.AddField(
            model_name='author',
            name='profile_image_url',
            field=models.URLField(max_length=2000, null=True),
        ),
    ]
