# Generated by Django 3.1.5 on 2021-01-27 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20210127_1716'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='pub_date_e',
            new_name='launch_date',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='pub_date_p',
            new_name='pub_date',
        ),
    ]
